# Generated by Django 5.2.4 on 2025-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=50, unique=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='diamondreport/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='diamondreport/')),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('carat', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
