# Generated by Django 5.2.4 on 2025-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondreport',
            name='carat',
        ),
        migrations.RemoveField(
            model_name='diamondreport',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='diamondreport',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='diamondreport',
            name='weight',
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='clarity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='colour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='cut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='dia_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='diamond_image',
            field=models.ImageField(blank=True, null=True, upload_to='diamonds/'),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='g_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='metal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diamondreport',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diamondreport',
            name='report_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
