# Generated by Django 5.2.4 on 2025-08-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('title_part1', models.CharField(blank=True, max_length=100, null=True)),
                ('title_part2', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph_1', models.TextField(blank=True, null=True)),
                ('paragraph_2', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
