# Generated by Django 5.2.4 on 2025-08-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='button_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
