# Generated by Django 5.2.4 on 2025-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_contactinfo_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiamondShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='diamond_shapes/')),
                ('category', models.CharField(choices=[('CLASSIC', 'Classic'), ('MODERN', 'Modern'), ('VINTAGE', 'Vintage'), ('UNIQUE', 'Unique')], max_length=20)),
                ('popularity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
