# Generated by Django 5.2.4 on 2025-09-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_diamondshape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondshape',
            name='category',
        ),
        migrations.RemoveField(
            model_name='diamondshape',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diamondshape',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='diamondshape',
            name='updated_at',
        ),
    ]
